version: "3.9"
services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: ["2181:2181"]

  kafka:
    image: bitnami/kafka:3.7
    ports: ["9092:9092"]
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on: [zookeeper]

  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-adtech}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-adtechpass}
      POSTGRES_DB: ${POSTGRES_DB:-adtech}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  adpulse:
    build: ./services/adpulse
    env_file:
      - .env
      - services/adpulse/.env
    ports: ["8001:8000"]
    depends_on: [kafka, postgres, redis]

  georeach:
    build: ./services/georeach
    env_file:
      - .env
      - services/georeach/.env
    ports: ["8002:8000"]
    depends_on: [postgres, redis]

  adshield:
    build: ./services/adshield
    env_file:
      - .env
      - services/adshield/.env
    ports: ["8003:8000"]
    depends_on: [redis, kafka]

volumes:
  pgdata: